name: Testing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8.*
          run_install: false

      # - name: Setup Chrome
      #   run: |
      #     add-apt-repository ppa:saiarcot895/chromium-beta
      #     apt-get update
      #     apt-get -y install chromium-browser
      #     chromium-browser --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Running tests
        run: |
          pnpm run build
          cd test-app
          pnpm run lint
          pnpm run test:ember
